# Generated by Django 5.0.6 on 2024-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_addressmodel_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Shop.product'),
        ),
    ]
