# Generated by Django 5.0.6 on 2024-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_order_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Canceled')], default=0),
        ),
    ]
