# Generated by Django 5.0.6 on 2024-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='area',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='house',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
