# Generated by Django 5.0.6 on 2024-08-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=0, help_text='0-pending,1-delivered'),
        ),
    ]
