# Generated by Django 5.0.6 on 2024-08-09 06:32

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to=Shop.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
