# Generated by Django 5.0.6 on 2024-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_carousel_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cod_order_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
